server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_management
    username: postgres
    password: 12345ali
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: your_spring_boot_app
